# NumPy

In [1]:
import numpy as np

L = list(range(10))

npa = np.array(L)
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
type(npa)

numpy.ndarray

In [3]:
npa4 = np.array([4.1, 3, 6])
npa4

array([4.1, 3. , 6. ])

# Multidimensional Array

In [5]:
x4 = np.random.randint(10, size = (3, 4))
x4

array([[9, 3, 9, 6],
       [4, 3, 2, 9],
       [5, 9, 3, 7]])

In [6]:
a1 = np.random.randint(5, size = (4, 6))
a1

array([[0, 2, 1, 4, 0, 3],
       [3, 2, 1, 0, 2, 3],
       [3, 0, 4, 0, 3, 3],
       [4, 0, 2, 3, 2, 0]])

# Indexing Arrays

In [15]:
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

x1
x1[0]

5

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x2[2, 3]

7

In [18]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [25]:
np.random.seed(0)
c = np.random.randint(5, size = (4,4))
c

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 0, 0, 4],
       [2, 1, 0, 1]])

In [26]:
c[2,1] = 9
c

array([[4, 0, 3, 3],
       [3, 1, 3, 2],
       [4, 9, 0, 4],
       [2, 1, 0, 1]])

In [27]:
c[1,3] = 19
c

array([[ 4,  0,  3,  3],
       [ 3,  1,  3, 19],
       [ 4,  9,  0,  4],
       [ 2,  1,  0,  1]])

In [31]:
c3_copy = c[2].copy()
c3_copy

array([4, 9, 0, 4])

In [30]:
c3_copy.reshape((4,1))

array([[4],
       [9],
       [0],
       [4]])