In [1]:
import numpy as np

In [4]:
rand = np.random.RandomState(6)
j = rand.randint(100, size = 20)
j

array([10, 73, 99, 84, 79, 80, 62, 25,  1, 75, 77, 57, 26, 33, 68, 33,  8,
        2, 76, 84])

In [6]:
a = [3, 11]
j[a]

array([84, 57])

In [7]:
[j[2], j[-4], j[8]]

[99, 8, 1]

In [8]:
b = np.array([[9,2],[-2,7]])
j[b]

array([[75, 99],
       [76, 25]])