In [18]:
import numpy as np

In [36]:
a = np.random.randint(5, size =(5,6))
a

array([[4, 1, 1, 0, 1, 1],
       [1, 1, 0, 4, 1, 0],
       [0, 3, 2, 1, 0, 3],
       [1, 1, 3, 4, 0, 1],
       [3, 4, 2, 4, 0, 3]])

In [37]:
a[:3, :4]

array([[4, 1, 1, 0],
       [1, 1, 0, 4],
       [0, 3, 2, 1]])

In [27]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [30]:
y = np.arange(10)
y[3:6]

array([3, 4, 5])

In [38]:
np.random.seed(1)
z = np.random.randint(10, size=(4, 4))
print(z)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]


In [40]:
z[:4, :2]

array([[5, 8],
       [0, 0],
       [6, 9],
       [5, 2]])

In [33]:
dict1 = {
    'Dallas': 'Cowboys',
    'Seattle': 'Seahawks'
}

In [35]:
print(dict1['Dallas'])

Cowboys


In [41]:
j = np.array([4, 5, 6])
k = np.array([1, 2, 3])
np.concatenate([j,k])

array([4, 5, 6, 1, 2, 3])