In [330]:
import numpy as np

In [331]:
np.random.seed(100)
con = np.random.random(size=20)
con

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333,
       0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375])

In [332]:
Q1 = np.sum(con)

In [333]:
Q2 = np.max(con)

In [334]:
con2 = np.random.random(size=(4,5))
con2

array([[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
       [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
       [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
       [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]])

In [335]:
Q3 = con2.min(1)

In [336]:
Q4 = np.mean(con2)

In [337]:
q5 = np.array([2, 3, np.nan, 5])
Q5 = np.nansum(q5)

In [338]:
q6a = np.random.random(size=4)
q6b = np.random.random(size=4)
Q6 = np.concatenate([q6a,q6b])

In [339]:
q7 = np.random.random(size=(4,4))
Q7 = np.concatenate([q7,q7])

In [340]:
q8 = np.random.random(size=(2,4))
Q8 = np.vstack((q7,q8))

In [341]:
q9a = np.vstack((q7,q7))
q9b = np.vstack((q9a,q7))
q9c = np.vstack((q9b,q8))
Q9 = np.vstack((q9c,q8))

In [342]:
q10 = np.random.random(size=(2,1))
Q10 = np.hstack((q8,q10))

In [343]:
q11 = np.random.random(size=20)
Q11a, Q11b = np.split(q11, [5])

In [344]:
Q12a, Q12b, Q12c = np.split(q11, [10,15])

In [345]:
q13 = np.random.random(size=(5,5))
q13


array([[0.45697913, 0.65894007, 0.25425752, 0.64110126, 0.20012361],
       [0.65762481, 0.77828922, 0.7795984 , 0.61032815, 0.30900035],
       [0.69773491, 0.8596183 , 0.62532376, 0.98240783, 0.97650013],
       [0.16669413, 0.02317814, 0.16074455, 0.92349683, 0.95354985],
       [0.21097842, 0.36052525, 0.54937526, 0.27183085, 0.46060162]])

In [346]:
Q13a, Q13b = np.split(q13, [3])

In [348]:
Q14a, Q14b = np.hsplit(q13, [3])